---
- name: Create Tower Nodes, then Create and Attach EBS Volumes for all tower nodes
  hosts: all #used to be localhost/IP of tower control node
  remote_user: ec2-user
  become: yes
  tasks:

    - name: Provision m5.2xlarge Tower Nodes
      amazon.aws.ec2:
        key_name: ATWAnsibleKeypair
        region: us-east-1
        instance_type: m5.2xlarge
        image: ami-0d4fb82d887858bc5
        wait: yes
        wait_timeout: 500
        count: 3
        instance_tags:
          Name: ansibleTowerNode #Rename later
          Owner: philBladen
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 30
            #if i can add multiple volumes up here then I wouldn't need the second task
          - device_name: /dev/xvdb
            volume_type: gp2
            volume_size: 20
            iops: 750
        monitoring: no
        vpc_subnet_id: subnet-0948e750ed5d6d3c5
        assign_public_ip: yes
        group: Docker-Swarm-SecGrp
      register: ec2_out

  #- name: create and attach volume for all created instances
   # amazon.aws.ec2_vol:
    #  instance: instance_ids #provided assuming there's 
     # with_items: '{{ec2_out.instances}}'
      #volume_size: 20
      #iops: 750
      #device_name: /dev/xvdb
      #region: us-east-1


